version: 2.0.{build}
image: Visual Studio 2022
configuration: Release
branches:
  only:
  - master
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore
build:
  project: Cinegy.TsMuxer.sln
  verbosity: minimal
after_build:
- pwsh: >-
    dotnet publish -c Release -r win-x64
    
    7z a Cinegy.TsMuxer-Win-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip $Env:APPVEYOR_BUILD_FOLDER\Cinegy.TsMuxer\bin\Release\netcoreapp3.1\win-x64\publish\tsmuxer.exe
    
    appveyor PushArtifact Cinegy.TsMuxer-Win-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip

    dotnet publish -c Release -r linux-x64

    7z a Cinegy.TsMuxer-Linux-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip $Env:APPVEYOR_BUILD_FOLDER\Cinegy.TsMuxer\bin\Release\netcoreapp3.1\linux-x64\publish\tsmuxer
    
    appveyor PushArtifact Cinegy.TsMuxer-Linux-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip

    7z a Cinegy.TsMuxer-PDB-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip $Env:APPVEYOR_BUILD_FOLDER\Cinegy.TsMuxer\bin
    
    appveyor PushArtifact Cinegy.TsMuxer-PDB-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION.zip